server:
  port: 8083

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: users_user
    password: users_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://users-db:5432/users_db
