server:
  port: 8082

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders_user
    password: orders_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

items-service:
  url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://orders-db:5432/orders_db

items-service:
  url: http://items-service:8081
