server:
  port: 8081

spring:
  application:
    name: items-service
  datasource:
    url: jdbc:postgresql://localhost:5432/items_db
    username: items_user
    password: items_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: items-service
    urls:
      - name: items-service
        url: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  server:
    port: 8081

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://items-db:5432/items_db

springdoc:
  swagger-ui:
    urls:
      - name: items-service
        url: /items/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  server:
    port: 8081
