server:
  port: 8085

spring:
  application:
    name: swagger-gateway

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Items Service
        url: http://localhost:8080/items/v3/api-docs
      - name: Orders Service
        url: http://localhost:8080/orders/v3/api-docs
      - name: Users Service
        url: http://localhost:8080/users/v3/api-docs
      - name: Auth Service
        url: http://localhost:8080/auth/v3/api-docs

microservices:
  items-service: http://localhost:8080
  orders-service: http://localhost:8080
  users-service: http://localhost:8080
  auth-service: http://localhost:8080

---
spring:
  config:
    activate:
      on-profile: docker

springdoc:
  swagger-ui:
    urls:
      - name: Items Service
        url: /items/v3/api-docs
      - name: Orders Service
        url: /orders/v3/api-docs
      - name: Users Service
        url: /users/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs

microservices:
  items-service: http://items-service:8081
  orders-service: http://orders-service:8082
  users-service: http://users-service:8083
  auth-service: http://auth-service:8084
